/** @type {import('tailwindcss').Config} */

module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: [
    "./app/**/*.{js,jsx,ts,tsx,css,ttf}",
    "./screen/**/*.{js,jsx,ts,tsx,css,ttf}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primaryBlack: "#171717",
        primaryBlue: "#0089FF",
        primaryTreatment: "#ED7390",
        primaryExercises: "#E59850",
        primaryCallDoctor: "#73E6ED",
        primaryDarkGray: "#565D6A",
        "custom-blue": "rgba(0, 137, 255, 0.30)",
        "custom-bg": "rgba(0, 122, 255, 0.04)",
        "custom-bg-burger": "rgba(36, 39, 96, 0.05)",
        "custom-icon": "rgba(0, 98, 255, 0.05)",
        "custom-colorBlue": "rgba(9, 15, 71, 0.95)",
        "custom-bg-white": "#FDFDFC",
        "custom-color-white": "rgba(240, 240, 240, 0.08)",
      },
      fontFamily: {
        // Кастомные шрифты
        "palatino-regular": "PalatinoLinotypeRegular",
        "palatino-bold": "PalatinoLinotypeBold",
        "oleo-bold": "OleoScriptBold",
        "oleo-regular": "OleoScriptRegular",
        "open-sans-regular": "OpenSansRegular",
        "open-sans-semibold": "OpenSansSemiBold",
        "open-sans-medium": "OpenSansMedium",
        "open-sans-light": "OpenSansLight",
        "open-sans-extraBold": "OpenSansExtraBold",
        "open-sans-bold": "OpenSansBold",
        "nunito-light": "NunitoLight",
        "nunito-extraLight": "NunitoExtraLight",
        "nunito-regular": "NunitoRegular",
        "nunito-medium": "NunitoMedium",
        "nunito-semibold": "NunitoSemiBold",
        "nunito-bold": "NunitoBold",
        "nunito-extraBold": "NunitoExtraBold",
        "assistant-light": "AssistantLight",
        "assistant-regular": "AssistantRegular",
        "assistant-extraLight": "AssistantExtraLight",
        "assistant-medium": "AssistantMedium",
        "assistant-semibold": "AssistantSemiBold",
        "assistant-bold": "AssistantBold",
        "assistant-extraBold": "AssistantExtraBold",
        "inter-regular": "InterRegular",
        "inter-semibold": "InterSemiBold",
        "inter-bold": "InterBold",
        "inter-extraBold": "InterExtraBold",
        "inter-extraLight": "InterExtraLight",
        "inter-light": "InterLight",
        "inter-medium": "InterMedium",
        "overPass-bold": "OverPassBold",
        "overpass-semibold": "OverPassSemiBold",
        "overpass-regular": "OverPassRegular",
        "overpass-medium": "OverPassMedium",
        "overpass-extraBold": "OverPassExtraBold",
      },
      boxShadow: {
        custom: "0px 4px 8px 0px rgba(0, 0, 0, 0.15)",
        "custom-sd": "0px 4px 4px rgba(0, 0, 0, 0.25)",
        customGray: "0px 4px 12px 0px rgba(13, 10, 44, 0.06)",
        customIcon: "0px 4px 12px 0px rgba(13, 10, 44, 0.06)",
      },
    },
  },
  plugins: [],
};
